In [1]:
class Value():
    

2

In [1]:
list_1=[1,3,2]
list_1[2]=5
list_1

[1, 3, 5]

In [4]:
tuple_1=("apple,3",23,5,645,89,5)
tuple_1.count(23)
len(tuple_1)

6

In [5]:
tuple_1[2:5]

(5, 645, 89)

In [6]:
tuple_1[3]=51 #Tuples are immutable#

TypeError: 'tuple' object does not support item assignment

In [7]:
nfruits=[("apple",56),("orange",23),("banana",89)]

In [8]:
n,m,o = nfruits #unpacking#
print(n,m,o)

('apple', 56) ('orange', 23) ('banana', 89)


In [10]:
tuple_2 = 5,6,5 #packing#
tuple_2

(5, 6, 5)

Next, **SETS**

In [12]:
set_1={5,89,5,12,3,6,7,9,6,5}
set(set_1) #to check the unique elements#

{3, 5, 6, 7, 9, 12, 89}

In [24]:
tuple_3 = ("a","m",9,"k","i","p","m","i")
set_2 = set(tuple_3)

In [21]:
set("unstoppable")

{'a', 'b', 'e', 'l', 'n', 'o', 'p', 's', 't', 'u'}

In [25]:
set_1.union(set_2)

{12, 3, 5, 6, 7, 89, 9, 'a', 'i', 'k', 'm', 'p'}

In [26]:
set_1.intersection(set_2)

{9}

In [27]:
set_1.issubset({1, 2, 3, 3, 4, 5})

False

**DICTIONARIES**

A dictionary is a key-value pairs, and each key maps to a corresponding value. It is defined by using a pair of braces { }, while the elements are a list of comma separated key:value pairs (note the key:value pair is separated by the colon, with key at front and value at the end).

Within a dictionary, elements are stored without order, therefore, you can not access a dictionary based on a sequence of index numbers. To get access to a dictionary, we need to use the key of the element - dictionary[key].

In [28]:
dict_1 = {'45kosp':33, 'sopc54':446, 'kopl24':22}
dict_1

{'45kosp': 33, 'sopc54': 446, 'kopl24': 22}

In [30]:
dict_1["kopl24"]

22

In [31]:
dict_1.keys()

dict_keys(['45kosp', 'sopc54', 'kopl24'])

In [32]:
dict_1.values()

dict_values([33, 446, 22])

In [33]:
len(dict_1)

3

In [34]:
library_dict = {}
library_dict['Cervantes'] = 'El ingenioso hidalgo Don Quijote de la Mancha'
library_dict

{'Cervantes': 'El ingenioso hidalgo Don Quijote de la Mancha'}

In [36]:
library_dict["Bradbury"] = "Farenheit 451"
library_dict

{'Cervantes': 'El ingenioso hidalgo Don Quijote de la Mancha',
 'Bradbury': 'Farenheit 451'}

In [37]:
list(library_dict) #turn keys to elements of a list#

['Cervantes', 'Bradbury']

**NUMPY Arrays**

NumPy is important in scientific computing, it is coded both in Python and C (for speed). On its website, a few important features for Numpy are listed:

* a powerful N-dimensional array object

* sophisticated (broadcasting) functions

* tools for integrating C/C++ and Fortran code

* useful linear algebra, Fourier transform, and random number capabilities

In [39]:
import numpy as np #import the library using a relatable name#

**Arrays/"Tensors"**

In [44]:
x_1 = np.array([56,89,45])
x_1

array([56, 89, 45])

In [46]:
x_2 = np.array([56,89,45,"m"])
x_2

array(['56', '89', '45', 'm'], dtype='<U21')

In [51]:
y_1 = np.array([[5,78,9,51],[2,3,1,4],[4,56,98,5]]) #careful with the brackets at the end
y_1

array([[ 5, 78,  9, 51],
       [ 2,  3,  1,  4],
       [ 4, 56, 98,  5]])

In [52]:
x_2.shape

(4,)

In [53]:
y_1.shape #size of matrix mxn#

(3, 4)

In [54]:
x_2.size #gets the total number of elements

4

In [55]:
y_1.size

12

In [56]:
z = np.arange(-5, 200, 1.23) #Create an array z from -5 to 200 with an increment 1.23#
z

array([-5.0000e+00, -3.7700e+00, -2.5400e+00, -1.3100e+00, -8.0000e-02,
        1.1500e+00,  2.3800e+00,  3.6100e+00,  4.8400e+00,  6.0700e+00,
        7.3000e+00,  8.5300e+00,  9.7600e+00,  1.0990e+01,  1.2220e+01,
        1.3450e+01,  1.4680e+01,  1.5910e+01,  1.7140e+01,  1.8370e+01,
        1.9600e+01,  2.0830e+01,  2.2060e+01,  2.3290e+01,  2.4520e+01,
        2.5750e+01,  2.6980e+01,  2.8210e+01,  2.9440e+01,  3.0670e+01,
        3.1900e+01,  3.3130e+01,  3.4360e+01,  3.5590e+01,  3.6820e+01,
        3.8050e+01,  3.9280e+01,  4.0510e+01,  4.1740e+01,  4.2970e+01,
        4.4200e+01,  4.5430e+01,  4.6660e+01,  4.7890e+01,  4.9120e+01,
        5.0350e+01,  5.1580e+01,  5.2810e+01,  5.4040e+01,  5.5270e+01,
        5.6500e+01,  5.7730e+01,  5.8960e+01,  6.0190e+01,  6.1420e+01,
        6.2650e+01,  6.3880e+01,  6.5110e+01,  6.6340e+01,  6.7570e+01,
        6.8800e+01,  7.0030e+01,  7.1260e+01,  7.2490e+01,  7.3720e+01,
        7.4950e+01,  7.6180e+01,  7.7410e+01,  7.8640e+01,  7.98

In [57]:
np.linspace(2,9,12) #linspace(a,b,n) generates an array of n equally spaced elements starting from a and ending at b.#

array([2.        , 2.63636364, 3.27272727, 3.90909091, 4.54545455,
       5.18181818, 5.81818182, 6.45454545, 7.09090909, 7.72727273,
       8.36363636, 9.        ])

In [2]:
import math
math.sqrt(4)

2.0

In [3]:
math.exp(math.log(10))

10.000000000000002

The computer truncates the numbers, at the end we have a small error "floating point error"/"truncation error"

In [4]:
math.comb?

Signature: math.comb(n, k, /)
Docstring:
Number of ways to choose k items from n items without repetition and without order.

Evaluates to n! / (k! * (n - k)!) when k <= n and evaluates
to zero when k > n.

Also called the binomial coefficient because it is equivalent
to the coefficient of k-th term in polynomial expansion of the
expression (1 + x)**n.

Raises TypeError if either of the arguments are not integers.
Raises ValueError if either of the arguments are negative.
Type:      builtin_function_or_method

In [5]:
1/0

ZeroDivisionError: division by zero

In [6]:
1/math.inf

0.0

In [7]:
math.inf*3

inf

In [8]:
math.inf/math.inf

nan

It is not a number.

In [9]:
complex(3,4)

(3+4j)

j = sqrt(-1) be careful when using j for indexes

In [10]:
59-78j

(59-78j)

In [11]:
type(45)

int

In [12]:
type(456.)

float

In [14]:
(4>3)+(5<-3) #VERY USEFUL FOR INDEXING, we get a numerical value doing an operation with the booleans.

1

In [15]:
whos

Variable   Type      Data/Info
------------------------------
math       module    <module 'math' from '/hom<...>311-x86_64-linux-gnu.so'>


Declared variables occupy RAM memory. The imported libraries also occupy memory.